// Bundles specs/*.json into src/specs.generated.ts so the Lambda bundle contains them.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { BusinessSpecSchema } from "../src/spec.js";

const specs = readdirSync("specs").filter((f) => f.endsWith(".json")).map((f) => BusinessSpecSchema.parse(JSON.parse(readFileSync(`specs/${f}`, "utf8"))));
writeFileSync("src/specs.generated.ts", `// GENERATED by scripts/gen-specs.ts. Do not edit.\nexport default ${JSON.stringify(specs, null, 2)} as unknown[];\n`);
console.log(`wrote ${specs.length} spec(s)`);
